---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .DockerName }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .UrlBase }}
        backend:
          serviceName: {{ .DockerName }}
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .DockerName }}
  labels:
    app: {{ .DockerName }}
    tier: api
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '8080'
    prometheus.io/path:   '{{ .UrlBase }}/metrics'
spec:
  selector:
    app: {{ .DockerName }}
    tier: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .DockerName }}
  labels:
    app: {{ .DockerName }}
    tier: api
spec:
  selector:
    matchLabels:
      app: {{ .DockerName }}
      tier: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .DockerName }}
        tier: api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .DockerName }}
        image: hub.docker.com/yaleits/{{ .DockerName }}
        volumeMounts:
        - name: {{ .DockerName }}-config
          mountPath: "/app/config"
          readOnly: true
        livenessProbe:
          httpGet:
            path: {{ .UrlBase }}/ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: {{ .DockerName }}-config
        secret:
          secretName: {{ .DockerName }}-config-json
        # envFrom:
        #   - configMapRef:
        #       name: {{ .DockerName }}-config
        #   - secretRef:
        #       name: {{ .DockerName }}-secrets
