---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: efs-api
spec:
  rules:
  - http:
      paths:
      - path: /v1/efs
        backend:
          serviceName: efs-api
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: efs-api
  labels:
    app: efs-api
    tier: api
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '8080'
    prometheus.io/path:   '/v1/efs/metrics'
spec:
  selector:
    app: efs-api
    tier: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-api
  labels:
    app: efs-api
    tier: api
spec:
  selector:
    matchLabels:
      app: efs-api
      tier: api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: efs-api
        tier: api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: efs-api
        image: hub.docker.com/yaleits/efs-api
        volumeMounts:
        - name: efs-api-config
          mountPath: "/app/config"
          readOnly: true
        livenessProbe:
          httpGet:
            path: /v1/efs/ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
      volumes:
      - name: efs-api-config
        secret:
          secretName: efs-api-config-json
        # envFrom:
        #   - configMapRef:
        #       name: {{ .DockerName }}-config
        #   - secretRef:
        #       name: {{ .DockerName }}-secrets
