replicaCount: 1

# image:
#   repository: hub.docker.com/yaleits/efs-api

# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
  rules:
    - paths: ['/v1/efs']

probePath: '/v1/efs/ping'
